import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from './providers'
import { UserProvider } from '../Context/UserProvider'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}){
  return (
  <UserProvider>
    <html lang="en" className='light'>
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  </UserProvider>
  );
}
export { RootLayout }
