import './globals.css'
import { Providers } from './providers'
import { UserProvider } from '../Context/UserProvider'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({children}){
  return (
  <UserProvider>
    <html lang="en" className='light'>
      <body suppressHydrationWarning={true}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  </UserProvider>
  );
}
export { RootLayout }
